### ISSUE TITLE
e10 compatibility

### ISSUE THREAD

**Issue by icaroperseo** [kumabook/stickynotes#68]
Hi!

As shown in the following [report](https://addons.mozilla.org/es/firefox/compatibility/reporter/sticky@filenamezero.dip.jp) your addon still it's not compatible so, would you be so kind to add e10 support? —Firefox performance improves considerably due to this feature—.

Thanks in advance and have a nice day!

**Comment by kumabook** [comment]
Hi, I submit new version that has compatible flag.
But unfortunately, I found the feature `jump to sticky` did not work perfectly(can't focus, only scroll) on multi process.
I think it is restriction of multi process,  so there is nothing we can do.

If possible, please check it and report me. 

Don't worry about latest 2 problem reports. because they are my report.
https://addons.mozilla.org/ja/firefox/compatibility/reporter/sticky@filenamezero.dip.jp

**Comment by kumabook** [comment]
support webextension at version 1.0.0
