### ISSUE TITLE
Sharing stickynotes.sqlite across profiles, running own stickynotes server

### ISSUE THREAD

**Issue by reikred** [kumabook/stickynotes#84]
Just wanted to understand if it is feasible to share the PROFILE/stickynotes.sqlite file across multiple firefox instances/profiles, so that all notes can be in one place. I could set up a symlink from my profiles to one common stickynotes.sqlite file, but I am a bit afraid to try :-).

Whether sharing possible or not, would be useful to set, as an option,  a different file location than PROFILE/stickynotes.sqlite. 

Also curious whether I can run my own stickynotes server (for privacy and independence). Is the server code on github? Any documentation?

**Comment by kumabook** [comment]
Hi,

Sorry for late reply, and thank you for your interest.

I tried to create symlink to `stickynotes.sqlite`.
It seems to be ok.

```
# quit firefox
mv ~/Library/Application\ Support/Firefox/Profiles/tgnnnxwx.default/stickynotes.sqlite ~/
ln -s ~/stickynotes.sqlite ~/Library/Application\ Support/Firefox/Profiles/tgnnnxwx.default/stickynotes.sqlite
# start firefox
```

Technically `diffrent file location`  is possible.
But there is a risk (ex: broken file, or security issue)
So I prefer to use stickynotes server.
And I'm thinking about sync with another platform (web page, iOS, android).

Backend server project is https://github.com/kumabook/stickynotes-backend.
It is written ruby on rails.
And it can be deploy on heroku.

But currently backend server location is not customizable, because it causes conflicts between servers and client.

you can try your own server by chaging the following file:
https://github.com/kumabook/stickynotes/blob/master/lib/config.js

**Comment by reikred** [comment]
Thank you for the tips, Hiroki. I have been busy with OS upgrades on the weekends but hope I will find time to try this out in not too long. In any case good to have this information available, I suspect other people exist that would like to try it.
